"""add idx_posts_author_id and idx_follows_following_id

Revision ID: 4c184f5dc39c
Revises: c6ba37f921ea
Create Date: 2026-04-01 00:58:47.039683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c184f5dc39c'
down_revision = 'c6ba37f921ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_author_id'))
        batch_op.create_index('idx_posts_author_id', ['author_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_posts_author_id')
        batch_op.create_index(batch_op.f('ix_posts_author_id'), ['author_id'], unique=False)

    # ### end Alembic commands ###
