"""add_idx_series_posts_post_id

Revision ID: 5523ceeb393f
Revises: 5d92b5bbdf0c
Create Date: 2026-04-10 01:06:06.103825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5523ceeb393f'
down_revision = '5d92b5bbdf0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
