"""add indexes for comments post_tags post_likes

Revision ID: 5c4b3411ca67
Revises: c6ba37f921ea
Create Date: 2026-04-06 03:55:48.800110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4b3411ca67'
down_revision = 'c6ba37f921ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comments_post_status_created', ['post_id', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.create_index('idx_post_likes_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.create_index('idx_post_tags_tag_id', ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_index('idx_post_tags_tag_id')

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_index('idx_post_likes_user_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('idx_comments_post_status_created')

    # ### end Alembic commands ###
