"""add blog_layout and banner_image_url to users

Revision ID: 684c84c39efb
Revises: 3ae876c3593f
Create Date: 2026-03-31 01:58:45.173154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684c84c39efb'
down_revision = '3ae876c3593f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_layout', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('banner_image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('banner_image_url')
        batch_op.drop_column('blog_layout')

    # ### end Alembic commands ###
