"""add content_format to posts

Revision ID: 7d29f46cdf24
Revises: d3b142695ad9
Create Date: 2026-03-26 01:44:44.728766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d29f46cdf24'
down_revision = 'd3b142695ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_format', sa.String(length=10), nullable=False, server_default='html'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('content_format')

    # ### end Alembic commands ###
