"""add composite index to visit_logs post_ip_time

Revision ID: 940ed6431ecc
Revises: bd7da55c642e
Create Date: 2026-04-10 09:46:44.852001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940ed6431ecc'
down_revision = 'bd7da55c642e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_visit_logs_post_ip_time', ['post_id', 'ip_address', 'visited_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_visit_logs_post_ip_time')

    # ### end Alembic commands ###
