"""add comment author_password_hash

Revision ID: a296bac8cb7e
Revises: aaaaaaaaaaaa
Create Date: 2026-03-25 04:59:16.859384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a296bac8cb7e'
down_revision = 'aaaaaaaaaaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('author_password_hash')

    # ### end Alembic commands ###
