"""add_idx_posts_author_id_follows_following_id

Revision ID: c6ba37f921ea
Revises: 79e90ed73d8d
Create Date: 2026-04-01 00:57:01.418472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ba37f921ea'
down_revision = '79e90ed73d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('idx_follows_following_id', ['following_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_author_id'), ['author_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_author_id'))

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('idx_follows_following_id')

    # ### end Alembic commands ###
