"""add thumbnail_url to posts

Revision ID: c888d26c19a1
Revises: 684c84c39efb
Create Date: 2026-03-31 03:47:46.343635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c888d26c19a1'
down_revision = '684c84c39efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')

    # ### end Alembic commands ###
