"""add blog customization to users

Revision ID: c891df1fe353
Revises: fffa879f6f26
Create Date: 2026-03-30 11:35:23.792625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c891df1fe353'
down_revision = 'fffa879f6f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blog_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('blog_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('social_links', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('social_links')
        batch_op.drop_column('website_url')
        batch_op.drop_column('blog_color')
        batch_op.drop_column('blog_title')

    # ### end Alembic commands ###
